package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBookreview<M extends BaseBookreview<M>> extends Model<M> implements IBean {

	public M setReviewID(java.lang.Integer reviewID) {
		set("reviewID", reviewID);
		return (M)this;
	}

	public java.lang.Integer getReviewID() {
		return get("reviewID");
	}

	public M setBookID(java.lang.Integer bookID) {
		set("bookID", bookID);
		return (M)this;
	}

	public java.lang.Integer getBookID() {
		return get("bookID");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public M setReviews(java.lang.String reviews) {
		set("reviews", reviews);
		return (M)this;
	}

	public java.lang.String getReviews() {
		return get("reviews");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

}
