package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public M setAddressID(java.lang.Integer addressID) {
		set("addressID", addressID);
		return (M)this;
	}

	public java.lang.Integer getAddressID() {
		return get("addressID");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setPostcode(java.lang.Integer postcode) {
		set("postcode", postcode);
		return (M)this;
	}

	public java.lang.Integer getPostcode() {
		return get("postcode");
	}

	public M setTelephone(java.lang.Integer telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public java.lang.Integer getTelephone() {
		return get("telephone");
	}

}
