package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBookinfo<M extends BaseBookinfo<M>> extends Model<M> implements IBean {

	public M setBookID(java.lang.Integer bookID) {
		set("bookID", bookID);
		return (M)this;
	}

	public java.lang.Integer getBookID() {
		return get("bookID");
	}

	public M setISBN(java.lang.String ISBN) {
		set("ISBN", ISBN);
		return (M)this;
	}

	public java.lang.String getISBN() {
		return get("ISBN");
	}

	public M setBook(java.lang.String book) {
		set("book", book);
		return (M)this;
	}

	public java.lang.String getBook() {
		return get("book");
	}

	public M setWriter(java.lang.String writer) {
		set("writer", writer);
		return (M)this;
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public M setPubFirm(java.lang.String pubFirm) {
		set("pubFirm", pubFirm);
		return (M)this;
	}

	public java.lang.String getPubFirm() {
		return get("pubFirm");
	}

	public M setPubTime(java.util.Date pubTime) {
		set("pubTime", pubTime);
		return (M)this;
	}

	public java.util.Date getPubTime() {
		return get("pubTime");
	}

	public M setCatalogID(java.lang.Integer catalogID) {
		set("catalogID", catalogID);
		return (M)this;
	}

	public java.lang.Integer getCatalogID() {
		return get("catalogID");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Float getPrice() {
		return get("price");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public M setAbstract(java.lang.String _abstract) {
		set("abstract", _abstract);
		return (M)this;
	}

	public java.lang.String getAbstract() {
		return get("abstract");
	}

	public M setSales(java.lang.Integer sales) {
		set("sales", sales);
		return (M)this;
	}

	public java.lang.Integer getSales() {
		return get("sales");
	}

	public M setPicture(java.lang.String picture) {
		set("picture", picture);
		return (M)this;
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

}
