package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShoppingcart<M extends BaseShoppingcart<M>> extends Model<M> implements IBean {

	public M setCartID(java.lang.Integer cartID) {
		set("cartID", cartID);
		return (M)this;
	}

	public java.lang.Integer getCartID() {
		return get("cartID");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public M setBookID(java.lang.Integer bookID) {
		set("bookID", bookID);
		return (M)this;
	}

	public java.lang.Integer getBookID() {
		return get("bookID");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

}
