package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public M setUserID(java.lang.Integer userID) {
		set("userID", userID);
		return (M)this;
	}

	public java.lang.Integer getUserID() {
		return get("userID");
	}

	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}

	public java.lang.String getRole() {
		return get("role");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setTelephone(java.lang.Integer telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public java.lang.Integer getTelephone() {
		return get("telephone");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

}
