package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setOrderID(java.lang.Integer orderID) {
		set("orderID", orderID);
		return (M)this;
	}

	public java.lang.Integer getOrderID() {
		return get("orderID");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public M setOrderDate(java.util.Date orderDate) {
		set("orderDate", orderDate);
		return (M)this;
	}

	public java.util.Date getOrderDate() {
		return get("orderDate");
	}

	public M setBookID(java.lang.Integer bookID) {
		set("bookID", bookID);
		return (M)this;
	}

	public java.lang.Integer getBookID() {
		return get("bookID");
	}

	public M setOrderNumber(java.lang.Integer orderNumber) {
		set("orderNumber", orderNumber);
		return (M)this;
	}

	public java.lang.Integer getOrderNumber() {
		return get("orderNumber");
	}

	public M setOrderStatus(java.lang.String orderStatus) {
		set("orderStatus", orderStatus);
		return (M)this;
	}

	public java.lang.String getOrderStatus() {
		return get("orderStatus");
	}

}
