package com.bambook.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSubcatalog<M extends BaseSubcatalog<M>> extends Model<M> implements IBean {

	public M setSCatalogID(java.lang.Integer sCatalogID) {
		set("sCatalogID", sCatalogID);
		return (M)this;
	}

	public java.lang.Integer getSCatalogID() {
		return get("sCatalogID");
	}

	public M setSCatalogName(java.lang.String sCatalogName) {
		set("sCatalogName", sCatalogName);
		return (M)this;
	}

	public java.lang.String getSCatalogName() {
		return get("sCatalogName");
	}

	public M setMCatalogID(java.lang.Integer mCatalogID) {
		set("mCatalogID", mCatalogID);
		return (M)this;
	}

	public java.lang.Integer getMCatalogID() {
		return get("mCatalogID");
	}

}
