package com.bambook.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("address", "addressID", Address.class);
		arp.addMapping("bookinfo", "bookID", Bookinfo.class);
		arp.addMapping("bookreview", "reviewID", Bookreview.class);
		arp.addMapping("maincatalog", "mCatalogID", Maincatalog.class);
		arp.addMapping("orders", "ID", Orders.class);
		arp.addMapping("shoppingcart", "cartID", Shoppingcart.class);
		arp.addMapping("subcatalog", "sCatalogID", Subcatalog.class);
		arp.addMapping("userinfo", "userID", Userinfo.class);
	}
}

