package com.bambook.model;

import com.bambook.model.base.BaseBookreview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookreview extends BaseBookreview<Bookreview> {
	public static final Bookreview dao = new Bookreview().dao();
}
