package com.bambook.model;

import com.bambook.model.base.BaseBookinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookinfo extends BaseBookinfo<Bookinfo> {
	public static final Bookinfo dao = new Bookinfo().dao();
}
