package com.bambook.model;

import com.bambook.model.base.BaseMaincatalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Maincatalog extends BaseMaincatalog<Maincatalog> {
	public static final Maincatalog dao = new Maincatalog().dao();
}
