package com.bambook.model;

import com.bambook.model.base.BaseShoppingcart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shoppingcart extends BaseShoppingcart<Shoppingcart> {
	public static final Shoppingcart dao = new Shoppingcart().dao();
}
