package com.bambook.model;

import com.bambook.model.base.BaseSubcatalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subcatalog extends BaseSubcatalog<Subcatalog> {
	public static final Subcatalog dao = new Subcatalog().dao();
}
